### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SauraJohnston** [FabianHenneke/ics2gcal#2]
I right clicked on an event on General Assembly's website 
Add to calendar - https://generalassemb.ly/education/designing-your-life/san-francisco/71687.ics
I selected "ics Add to Calendar" and my email address where my calendar is
I then see:
<img width="508" alt="Screen Shot 2019-03-13 at 3 36 22 PM" src="https://user-images.githubusercontent.com/22824430/54319152-e119de00-45a5-11e9-85bb-55d31eb7cc4f.png">
And then: 
<img width="373" alt="Screen Shot 2019-03-13 at 3 36 26 PM" src="https://user-images.githubusercontent.com/22824430/54319160-e5de9200-45a5-11e9-956c-0ee56e3db815.png">

**Comment by FabianHenneke** [comment]
Thank you for the report! There are two separate issues here:

1. The .ics file mentions a timezone (America/Los_Angeles), but does not use it. According to the specification, this means that all date/time values in the file are to be interpreted as "floating time", i.e., local to the calendar they are being imported into. This is not something I can do anything about, but you could let generalassemb.ly know about this issue.

2. The "floating" times are not correctly translated into the format expected by the Google Calendar API. This is something for me to fix.

**Comment by FabianHenneke** [comment]
With commit b93477ef51ce1a22af995a5a5bc20c46e8ea8e8f the default time zone of your calendar is now used if the ics file does not (correctly) specify a time zone for the event. The change is rolling out as version 0.7.0. Please let me know whether it fixes the issue for you.

**Comment by SauraJohnston** [comment]
thank you!
