### ISSUE TITLE
Can't create events!

### ISSUE THREAD

**Issue by emrah7celik** [FabianHenneke/ics2gcal#3]
The extension, while it can see my calendars, is unable to import ics files. Import fails with the error message: "Can't create the event." I tried re-authorising with my Calendar account but upon clicking the extension button nothing happens and there is no other option to do this.

**Comment by FabianHenneke** [comment]
Could you provide me with the link to the ics file for which this is happening? Have you tried other ics files? I suspect this is an issue with a particular file.

**Comment by emrah7celik** [comment]
> Could you provide me with the link to the ics file for which this is happening? Have you tried other ics files? I suspect this is an issue with a particular file.

You are right. I tried a different website that directly linked an ics and it worked. [This one](https://iom.webex.com/iom/j.php?MTID=m6a93e9213706c890e4bbaf33878fbe33) that I originally tried doesn't directly link the ics and therefore leads to the error.
